Numpy arrays are *homogeneous amd typed arrays*, meaning that all elements in a numpy array have the same data type of fixed sizes. This is advantageous because it permits generic array operations without having to check the type nor size in memory for each element.

In [1]:
import numpy as np

In [2]:
np.ndarray?

In [3]:
data = np.array([[1, 2], [3, 4], [5, 6]])
# data has attributes:
# shape - the number of elements for each dimension
# size - the total number of elements in the array
# ndim - the number of dimensions
# nbytes - the number of bytes to store the data (depends on what the type is)
# dtype - the type of the data

In [4]:
type(data)

numpy.ndarray

In [5]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
data.shape # the number of elements for each dimension

(3, 2)

In [7]:
data.size # the total number of elements in the array

6

In [8]:
data.ndim # the number of dimensions

2

In [9]:
data.nbytes # the number of bytes to store the data (depends on what the type is)

24

In [11]:
data.dtype # the type of the data

dtype('int32')

In [53]:
data2 = np.array([[1, 2], [3, 4], [5, 6]], dtype="int8")

In [52]:
data2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int8)

In [55]:
np.array([1, 2, 3], dtype=int)

array([1, 2, 3])

In [57]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [59]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

### Casting types


In [60]:
data = np.array([1, 2, 3], dtype=float)

In [64]:
data

array([1., 2., 3.])

In [65]:
data.dtype

dtype('float64')

In [66]:
data = np.array(data, dtype=int) # casting float to int

In [67]:
data

array([1, 2, 3])

In [72]:
data = data.astype(float) # casting using astype

In [73]:
data

array([1., 2., 3.])

#### When making operations, the dtypes can be promoted

In [75]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [76]:
Out[75].dtype

dtype('complex128')

In [78]:
np.sqrt(np.array([-1, 0, 1]))

C:\Users\phila\AppData\Local\Temp/ipykernel_6856/208196152.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np.array([-1, 0, 1]))


array([nan,  0.,  1.])

In [79]:
np.sqrt(np.array([-1, 0, 1]), dtype=complex)

array([0.+1.j, 0.+0.j, 1.+0.j])

### Order of array Data in Memory

In [80]:
arr = np.array([[1, 2, 3, 4], [5, 4, 3, 6], [5, 4, 3, 6], [5, 9, 123, 3]])

In [81]:
arr

array([[  1,   2,   3,   4],
       [  5,   4,   3,   6],
       [  5,   4,   3,   6],
       [  5,   9, 123,   3]])

In [84]:
arr.strides # "Strides is the factor by which the index
            # for the corresponding axis is multiplied
            # when calculating the memory offset (in bytes)""

(16, 4)

### Creating arrays in multiple ways

In [90]:
# np.array - creates an arreay from a iterable
iterable = list((1, 2, 3, 4, 5))
data = np.array(iterable)

In [101]:
f"{data.ndim = } | {data.shape = }"

'data.ndim = 1 | data.shape = (5,)'

In [105]:
# np.zeros and np.ones - creates an array and fills it with 0s and 1s
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [106]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [107]:
# The dtype can be specified
np.ones(4, dtype="int8")

array([1, 1, 1, 1], dtype=int8)

In [109]:
# np.full can create an array of specified dimensions and fill it with a specified value
np.full((3, 5), 10, dtype="int8")

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]], dtype=int8)

In [118]:
# np.diag creates a diagonal array with its diagonal having specified values and 0 anywhere else.
# Which diagonal is filled can also be specified. By default, k=0
np.diag((1, 3, 4, 2))

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 2]])

In [121]:
np.diag((1, 3, 4, 2), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 2, 0]])

In [123]:
# np.arange(n, m, k) to create an array from m to n, in k incremental steps
np.arange(0.0, 10, 1) # from 0.0 to 10 exclusive in steps of 1.0

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [126]:
# np.linspace(j, k, n) - creates an array with n values from j to k, evenly spaced
np.linspace(0, 10, 11) # 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [129]:
# np.logspace(j, k, n) - similar to np.linspace, but creates n values from j to k ligarithmically distributed
np.logspace(0, 10, 10)

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

**Continuar na página**: 55 - meshgrids